apiVersion: v1
kind: Namespace
metadata:
  name: {{ namespace }}
  labels:
    synpulse8.com/env: {{ environment_abbreviation }}
    istio-injection: enabled
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: {{ helmrelease_name }}
  namespace: {{ namespace }}
spec:
  interval: 1h # Any change to values triggers recon, this is just for periodic recon only
  targetNamespace: {{ namespace }}
  install:
    disableWait: true # this is to prevent the helm release from waiting for the pods to be ready
    remediation:
      retries: 0 # retry indefinitely in case of failure
  chart:
    spec:
      chart: pulse8-microservice
      version: "0.1.*"
      sourceRef:
        name: pulse8-helm-charts-oci
        namespace: flux-system
        kind: HelmRepository
  values:
    nameOverride: {{ chart_name }}
    envName: {{ environment_abbreviation }}
    automation:
      enabled: true
      filePath: {{ automatic_deployment_filepath }} # must point to a folder containing this file
    image:
      repository: {{ image_repository }}
      tag: "0000000000" # {"$imagepolicy": "{{ namespace }}:{{ chart_name }}:tag"}
      pullSecret:
        name: synpulse-jfrog-docker-credential
        create: true{% if env_vars %}
    env: # Environment variables to be set for the container
      {% for env_variable_line in env_vars %}
      {{ var_line }}
      {% endfor %}
    {% endif %}{% if env_secret_params %}
    envSecretParameters: # Environment variables from AWS SSM Parameter Store - instead of specifying a value, specify the path from AWS SSM
      {% for env_variable_line in env_secret_params %}
      {{ var_line }}
      {% endfor %}
    {% endif %}
    service:
      ports:
        - name: primary-port
          internalPort: {{ application_port }} # what port does your container expose?
    ingress:
      enabled: true{% if ingress_route != "/"  %}
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$3
        nginx.ingress.kubernetes.io/x-forwarded-prefix: /$1
      {% endif %}
      hosts:
        - host: {{ environment_abbreviation }}.{{ chart_name }}.aws.synpulse8.com
          paths:
            - path: {{ ingress_route }}
              pathType: Prefix
      tls:
        - secretName: {{ chart_name }}-tls # this will be created dynamically, its name doesn't matter
          hosts:
            - {{ environment_abbreviation }}.{{ chart_name }}.aws.synpulse8.com # must match your host definition above
    resources:
      requests:
        cpu: 100m
        memory: 512Mi