---
- name: Install k3d
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install k3d with curl
      ansible.builtin.shell: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      when: ansible_facts['os_family'] == "Darwin" or ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Suse" or ansible_facts['os_family'] == "Gentoo" or ansible_facts['os_family'] == "Archlinux" or ansible_facts['os_family'] == "FreeBSD"
    - name: Install k3d with chocolatey
      ansible.builtin.shell: choco install k3d
      when: ansible_facts['os_family'] == "Windows"
- name: Install devspace
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install devspace using npm
      community.general.npm:
        name: devspace
        global: true
- name: Install pnpm
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install pnpm using npm
      community.general.npm:
        name: pnpm
        global: true
- name: Install kubectl
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install kubectl with apt (Debian-based Linux)
      ansible.builtin.apt:
        pkg:
          - kubectl
      when: ansible_facts['os_family'] == "Debian"
    - name: Install kubectl with Homebrew (macOS)
      community.general.homebrew:
        name: kubernetes-cli
        state: present
        update_homebrew: true
      when: ansible_facts['os_family'] == "Darwin"
    - name: Install kubectl with chocolatey (Windows)
      win_chocolatey:
        name: kubernetes-cli
        state: present
      when: ansible_facts['os_family'] == "Windows"
- name: Install helm
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install helm with apt (Debian-based Linux)
      ansible.builtin.apt:
        pkg:
          - helm
      when: ansible_facts['os_family'] == "Debian"
    - name: Install helm with Homebrew (macOS)
      community.general.homebrew:
        name: helm
        state: present
        update_homebrew: true
      when: ansible_facts['os_family'] == "Darwin"
    - name: Install helm with chocolatey (Windows)
      win_chocolatey:
        name: kubernetes-helm
        state: present
      when: ansible_facts['os_family'] == "Windows"
- name: Install flux
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install flux with curl (macOS and Linux)
      ansible.builtin.shell: curl -s https://fluxcd.io/install.sh | bash
      become: true
      when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Darwin"
    - name: Install helm with chocolatey (Windows)
      win_chocolatey:
        name: flux
        state: present
      when: ansible_facts['os_family'] == "Windows"